#!/usr/bin/env bash
# Mirror selected host environment variables into the atelier-smp VM.
# Idempotent. Re-run any time you rotate tokens or change proxy settings.
#
# What gets forwarded (if set on host):
#   ANTHROPIC_BASE_URL, ANTHROPIC_AUTH_TOKEN, ANTHROPIC_API_KEY
#   API_TIMEOUT_MS
#   GITHUB_TOKEN (used by `gh auth login --with-token` if non-empty)
#
# Usage:
#   ./setup/host-passthrough.sh            # push host env into VM
#   ./setup/host-passthrough.sh --show     # print current VM-side env
set -euo pipefail

VM_NAME="${DEVBOX_VM:-atelier-smp}"
# NOTE: $HOME on the host is the macOS path (/Users/lazy). The VM is Linux, so
# its equivalent home is /home/<user>. Hardcode the VM-side path.
VM_USER="${VM_USER:-lazy}"
DEST="/home/${VM_USER}/.config/environment.d/host-proxy.conf"

FORWARD_VARS=(
  ANTHROPIC_BASE_URL
  ANTHROPIC_AUTH_TOKEN
  ANTHROPIC_API_KEY
  API_TIMEOUT_MS
  GITHUB_TOKEN
)

require_orb() {
  command -v orbctl >/dev/null 2>&1 || {
    echo "[passthrough] OrbStack missing — brew install --cask orbstack" >&2
    exit 1
  }
  export PATH="/opt/homebrew/bin:$PATH"
}

show() {
  require_orb
  echo "[passthrough] $DEST inside $VM_NAME:"
  orbctl run -m "$VM_NAME" -- bash -c "cat '$DEST' 2>/dev/null || echo '(not set)'"
  exit 0
}

[[ "${1:-}" == "--show" ]] && show

require_orb

# Build the env file on the host in /tmp, then push it into the VM.
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
  echo "# Generated by setup/host-passthrough.sh on $(date -u +%FT%TZ)"
  echo "# Source: host shell env. Re-run this script to refresh."
  echo
  for v in "${FORWARD_VARS[@]}"; do
    if [[ -n "${!v-}" ]]; then
      # Quote values that contain spaces/specials; escape single quotes.
      val="${!v//\'/\'\\\'\'}"
      printf "export %s='%s'\n" "$v" "$val"
      echo "   [passthrough] $v=***" >&2
    else
      echo "# $v not set on host — skipped" >&2
    fi
  done
} > "$tmp"

# Ensure target dir exists in VM
orbctl run -m "$VM_NAME" bash -c "mkdir -p '$(dirname "$DEST")'"

# Copy file in via stdin (avoids needing push/pull for one small file)
cat "$tmp" | orbctl run -m "$VM_NAME" bash -c "cat > '$DEST'"

echo
echo "[passthrough] wrote $DEST inside $VM_NAME"
echo "[passthrough] new shells in the VM will pick it up automatically (via ~/.bashrc.d/ include)."
echo "[passthrough] for an already-running session: source $DEST"
